### ISSUE TITLE
Output file

### ISSUE THREAD

**Issue by BonShillings** [CraigBryan/tweet-mood-analyzer#6]
For a collection of tokens, we need to find a way to write the tokens to the output file as word instead of u'word'.

**Comment by CraigBryan** [comment]
I'll be doing the bag of words thing soon, so that will likely fix this? Instead of having one feature as a the whole string, each word in the dictionary will be a feature, and the data for a given tweet for each word will be the number of occurrences.

For a quick fix, I would change the feature from using the raw token instance variable (as a list), and instead use a function that returns an single string, or re-encodes the list as ASCII and returns that.

**Comment by BonShillings** [comment]
Ya this would be perfect I think. Right now I'm just trying to pass the tokens to Weka's StringToWordVector to get the bag of words, but if we create the bag of words in python, then we no longer even have the issue.

The main problem is performance is really slow in weka if we use their StringToWordVector parser, because it makes a lot of unnecessary extra features and it goes vvvery slow. Although I think a mixture is usable, BOW output is maybe even better.

**Comment by CraigBryan** [comment]
The bag of words is done, but I haven't tested it in Weka. When you get a chance, try it and we'll close this if it actually works.

**Comment by BonShillings** [comment]
Tested in Weka, the result file is too large for Weka if we use everything, but I added a few lines of code that allow us to trim unfrequent terms. It works really great now
